apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out temp_k8s/
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafdrop
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out temp_k8s/
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kafdrop
    spec:
      containers:
        - env:
            - name: JVM_OPTS
              value: -Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
            - name: KAFKA_BROKERCONNECT
              value: kafka:9092
          image: obsidiandynamics/kafdrop
          name: kafdrop
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
