apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out temp_k8s/
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pushgateway
  name: pushgateway
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: pushgateway
status:
  loadBalancer: {}
